### ISSUE TITLE
Burglar's Pack missing descriptive text

### ISSUE THREAD

**Issue by jeremyritter** [unRARed/freednd#46]
Other adventuring gear packs have their descriptive text, Burglar's Pack is missing.

**Comment by unRARed** [comment]
Thanks! Looks like some equipment has nested content... https://www.dnd5eapi.co/api/equipment/burglars-pack

I'll need to think about how to mirror this from the DB.

**Comment by unRARed** [comment]
This was fixed on a prior update

<img width="517" alt="Screen Shot 2020-10-15 at 11 53 03 PM" src="https://user-images.githubusercontent.com/1447940/96222717-9a3e5800-0f41-11eb-8e74-168d3d991ff5.png">
